const rolesData = [
    {
        roleID: 'R0001',
        roleName: 'TestEnsure Admin',
        status: 1,
    },
    {
        roleID: 'R0002',
        roleName: 'Client Admin',
        status: 1,
    },
    {
        roleID: 'R0003',
        roleName: 'QA Engineer',
        status: 1,
    },
    {
        roleID: 'R0004',
        roleName: 'Release Manager',
        status: 1,
    },
    {
        roleID: 'R0005',
        roleName: 'Executor',
        status: 1,
    },
    {
        roleID: 'R0006',
        roleName: 'Executives',
        status: 1,
    },
]

const validationData = {
    ModuleValidate: {
        executionDataRules: {
            testNodeProps: [
                'testCaseID',
                'testCaseTitle',
                'testCaseDescription',
                'dependsOn',
                'tags',
                'testCaseSteps',
            ],
            validNavActions: [
                'login',
                'typeText',
                'clickElement',
                'clickLastElement',
                'extractDataFromPDF',
                'doubleClickElement',
                'typeTextWithEnter',
                'typeTextWithTabKey',
                'textClearInputs',
                'zoomOut',
                'savePDF',
                'switchToPatentWindow',
                'zoom',
                'frameSwitch',
                'frameSwitchIndex',
                'windowSwitch',
                'scrollTo',
                'selectCheckbox',
                'unSelectCheckbox',
                'selectRadioButton',
                'getText',
                'filepath',
                'Subtract',
                'clickPurchaseOrderAdvice',
                'clickLastCheckBoxInList',
                'copyClipboard',
                'getPlannedOrder',
                'getPeggingOrder',
                'clickPurchaseOrder',
                'clickPurchaseOrderInWB',
                'clickShadowElement',
                'splitText',
                'keyBoardEvent',
                'sleep',
                'randomString',
                'randomNumber',
                'module',
                'sendDateElement',
                'typeTextAndEnter',
                'mouseHoverElement',
                'scrollToElement',
                'uploadFile',
                'uploadFileInBox',
                'scrollDown',
                'switchToTab',
                'typeGeneratedName',
                'switchToTab',
                'scrollDownField',
                'compareString',
                'api',
                'apiCall',
                'getListofFollowersAdded',
                'getTextField',
                'actionSelector',
                'readDataAndStoreInObject',
                'save',
                'loop',
                'modifiedUrl',
                'clickIndexElement',
                'getText2',
                'leavesDuration',
                'getElementsList',
                'comparePdfData',
                'compareExcelData',
                'weekDuration',
                'timesheetsPeriod',
                'readDataFromObject',
                'copyUrl',
                'pageNavigation',
                'getCurrentWeekAndYear',
                'getCurrentWeek',
            ],
            validValidateActions: [
                'isDisplayed',
                'isElementPresent',
                'verifyStrings',
                'isElementNotPresent',
                'verifyText',
                'compareListItems',
                'compareList',
                'isAmountDisplayed',
                'excelData',
                'isLoaderNotPresent',
                'addition',
            ],
        },
        testDataRules: {
            key: 'value',
        },
    },
}

const roleManagersData = [
    {
        components: [
            {
                home: {
                    view: true,
                },
                projects: {
                    view: true,
                    create: true,
                    edit: true,
                    delete: true,
                },
                projectModules: {
                    view: true,
                    create: true,
                    edit: true,
                    delete: true,
                },
                releases: {
                    view: true,
                    create: true,
                    delete: true,
                    clone: true,
                    run: true,
                    dashboard: true,
                    edit: true,
                },
                releaseTestCases: {
                    view: 'true',
                    fileExport: 'true',
                    screenshots: 'true',
                    logs: 'true',
                    comments: 'true',
                    runHistory: 'true',
                    changeLog: 'true',
                    issues: 'true',
                },
                testRuns: {
                    view: true,
                    edit: true,
                    stopRun: true,
                    releaseDetails: true,
                    dashboard: true,
                    reRun: false,
                },
                testRunsTestCases: {
                    view: 'true',
                    fileExport: 'true',
                    screenshots: 'true',
                    logs: 'true',
                    comments: 'true',
                    runHistory: 'true',
                    changeLog: 'true',
                    issues: 'true',
                    video: 'true',
                },
                report: {
                    view: true,
                },
            },
        ],
        rid: 'DEFAULT',
        roleId: 'DEFAULT',
        clientId: 'DEFAULT',
    },
    {
        components: [
            {
                home: {
                    view: true,
                },
                projects: {
                    view: true,
                    create: true,
                    edit: true,
                    delete: true,
                },
                projectModules: {
                    view: true,
                    create: true,
                    edit: true,
                    delete: true,
                },
                releases: {
                    view: true,
                    create: true,
                    delete: true,
                    clone: true,
                    run: true,
                    dashboard: true,
                    edit: true,
                },
                releaseTestCases: {
                    view: 'true',
                    fileExport: 'true',
                    screenshots: 'true',
                    logs: 'true',
                    comments: 'true',
                    runHistory: 'true',
                    changeLog: 'true',
                    issues: 'true',
                },
                testRuns: {
                    view: true,
                    edit: true,
                    stopRun: true,
                    releaseDetails: true,
                    dashboard: true,
                    reRun: false,
                },
                testRunsTestCases: {
                    view: 'true',
                    fileExport: 'true',
                    screenshots: 'true',
                    logs: 'true',
                    comments: 'true',
                    runHistory: 'true',
                    changeLog: 'true',
                    issues: 'true',
                    video: 'true',
                },
                report: {
                    view: true,
                },
            },
        ],
        rid: 'CLIENT_ADMIN',
        roleId: 'CLIENT_ADMIN',
        clientId: 'CLIENT_ADMIN',
    },
]

export default { rolesData, validationData, roleManagersData }
